name: build

on:
  push:
    branches: [ main, f-ci-action ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.6'
      - run: dart --version
      - run: flutter --version
      - name: build fair_example
        working-directory: fair/example
        run: |
          flutter build apk --target-platform android-arm64
          flutter build ios --release --no-codesign
      - name: build sample project my_app
        working-directory: samples/my_app
        run: |
          flutter build apk --target-platform android-arm64
          flutter build ios --release --no-codesign